# 8-queens Problem

In [2]:
import mlrose
import numpy as np

In [3]:
# Define alternative N-Queens fitness function for maximization problem
def queens_max(state):
    # Initialize counter
    fitness_cnt = 0

    # For all pairs of queens
    for i in range(len(state) - 1):
         for j in range(i + 1, len(state)):
            # Check for horizontal, diagonal-up and diagonal-down attacks
            if (state[j] != state[i]) \
            and (state[j] != state[i] + (j - i)) \
            and (state[j] != state[i] - (j - i)):
                # If no attacks, then increment counter
                fitness_cnt += 1

    return fitness_cnt

# Initialize custom fitness function object
fitness_cust = mlrose.CustomFitness(queens_max)

In [6]:
fitness = mlrose.Queens()

In [7]:
problem = mlrose.DiscreteOpt(length = 8, fitness_fn = fitness, maximize = False, max_val = 8)
# problem = mlrose.DiscreteOpt(length = 8, fitness_fn = queens_max, maximize = True, max_val = 8)

### 1. SA

In [8]:
# Define decay schedule
schedule = mlrose.ExpDecay()

# Define initial state
init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Solve problem using simulated annealing
best_state, best_fitness = mlrose.simulated_annealing(problem, schedule = schedule,
                                                      max_attempts = 10, max_iters = 1000,
                                                      init_state = init_state, random_state = 1)

print(best_state)

print(best_fitness)

[6 4 7 3 6 2 5 1]
2.0


In [14]:
# Define decay schedule
schedule = mlrose.ExpDecay()

# Define initial state
init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Solve problem using simulated annealing
best_state, best_fitness = mlrose.simulated_annealing(problem, schedule = schedule,
                                                      max_attempts = 100, max_iters = 1000,
                                                      init_state = init_state, random_state = 1)

print(best_state)

print(best_fitness)

[4 1 3 5 7 2 0 6]
0.0


### 2. RHC

In [33]:
# Define initial state
init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Solve problem using random_hill_climb
best_state2, best_fitness2 = mlrose.random_hill_climb(problem, max_attempts = 10, 
                                                      max_iters = 1000, restarts = 10,
                                                      init_state = init_state, curve = False, random_state = 1)

print(best_state2)

print(best_fitness2)

[0 6 3 7 7 1 2 5]
2.0


In [35]:
# Define initial state
init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Solve problem using random_hill_climb
best_state2, best_fitness2 = mlrose.random_hill_climb(problem, max_attempts = 100, 
                                                      max_iters = 1000, restarts = 100,
                                                      init_state = init_state, curve = False, random_state = 1)

print(best_state2)

print(best_fitness2)

[3 1 6 2 5 7 0 4]
0.0


### 3. GA

In [36]:
# Define initial state
init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Solve problem using genetic_alg
best_state3, best_fitness3 = mlrose.genetic_alg(problem, pop_size = 200, 
                                                mutation_prob = 0.1, max_attempts = 10, max_iters = 1000, 
                                                curve = False, random_state = 1)

print(best_state3)

print(best_fitness3)

[4 0 4 6 1 3 7 7]
2.0


In [37]:
# Define initial state
init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Solve problem using genetic_alg
best_state3, best_fitness3 = mlrose.genetic_alg(problem, pop_size = 200, 
                                                mutation_prob = 0.1, max_attempts = 100, max_iters = 1000, 
                                                curve = False, random_state = 1)

print(best_state3)

print(best_fitness3)

[4 0 5 3 1 6 2 5]
1.0


### 4. MIMIC

In [38]:
# Define initial state
init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Solve problem using MIMIC
best_state4, best_fitness4 = mlrose.mimic(problem, pop_size = 200, 
                                          keep_pct = 0.2, max_attempts = 10, max_iters = 1000, 
                                          curve = False, random_state = 1, fast_mimic = False)

print(best_state4)

print(best_fitness4)

[7 4 1 0 6 3 6 2]
2.0


In [39]:
# Define initial state
init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Solve problem using MIMIC
best_state4, best_fitness4 = mlrose.mimic(problem, pop_size = 200, 
                                          keep_pct = 0.2, max_attempts = 100, max_iters = 1000, 
                                          curve = False, random_state = 1, fast_mimic = False)

print(best_state4)

print(best_fitness4)

[7 4 1 0 6 3 6 2]
2.0


### Combine

In [6]:
def n_queens_compare(n, runs = 100):
    
    # define problem
    fitness = mlrose.Queens()
    problem = mlrose.DiscreteOpt(length = n, fitness_fn = fitness, maximize = False, max_val = n)
    
    # randomly define initial states
    np.random.seed(2)
    RHC_accu = []
    SA_accu = []
    GA_accu = []
    MIMIC_accu = []
    
    for i in range(runs):
        init_state = np.random.randint(low = 0, high = n, size = n)
        RHC_state, RHC_fitness = mlrose.random_hill_climb(problem, max_attempts = 10, 
                                                      max_iters = 1000, restarts = 10,
                                                      init_state = init_state, curve = False, random_state = 1)
        
        schedule = mlrose.ExpDecay()
        SA_state, SA_fitness = mlrose.simulated_annealing(problem, schedule = schedule,
                                                              max_attempts = 10, max_iters = 1000,
                                                              init_state = init_state, random_state = 1)
        
        GA_state, GA_fitness = mlrose.genetic_alg(problem, pop_size = 200, 
                                                mutation_prob = 0.1, max_attempts = 10, max_iters = 1000, 
                                                curve = False, random_state = 1)

        MIMIC_state, MIMIC_fitness = mlrose.genetic_alg(problem, pop_size = 200, 
                                                mutation_prob = 0.1, max_attempts = 10, max_iters = 1000, 
                                                curve = False, random_state = 1)
        
        RHC_accu.append(RHC_fitness)
        SA_accu.append(SA_fitness)
        GA_accu.append(GA_fitness)
        MIMIC_accu.append(MIMIC_fitness)
    
    print(RHC_state, RHC_fitness, SA_state, SA_fitness, GA_state, GA_fitness, MIMIC_state, MIMIC_fitness)
    return [RHC_accu, SA_accu, GA_accu, MIMIC_accu]
        

In [87]:
res = n_queens_compare(8, runs = 1000)
print('RHC', np.mean(res[0]))
print('SA', np.mean(res[1]))
print('GA', np.mean(res[2]))
print('MIMIC', np.mean(res[3]))

[4 6 0 3 5 7 2 6] 1.0 [7 3 0 2 5 1 6 4] 0.0 [4 0 4 6 1 3 7 7] 2.0 [4 0 4 6 1 3 7 7] 2.0
RHC 1.001
SA 0.003
GA 2.0
MIMIC 2.0


In [7]:
res1 = n_queens_compare(16, runs = 100)
print('RHC', np.mean(res1[0]))
print('SA', np.mean(res1[1]))
print('GA', np.mean(res1[2]))
print('MIMIC', np.mean(res1[3]))

[ 5  0  2 11  8 10  3 14 12  1  0 13 15  4  9  7] 5.0 [14 11  5  3  7  0  2 13  9  1  6 13 10  0 12  4] 5.0 [ 4  0  5 15  5  1  8  3 10  7  3 13  9 11 14  2] 9.0 [ 4  0  5 15  5  1  8  3 10  7  3 13  9 11 14  2] 9.0
RHC 4.98
SA 5.01
GA 9.0
MIMIC 9.0


# 4-peaks Problem

### 4.1 SA

In [27]:
fitness = mlrose.FourPeaks(t_pct=0.15)
state = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0])
fitness.evaluate(state)

36

In [44]:
peak_problem = mlrose.DiscreteOpt(length = 12, fitness_fn = fitness, maximize = True, max_val = 2)

In [45]:
# Define decay schedule
schedule = mlrose.ExpDecay()

# Define initial state
init_state = np.array([1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0])

# Solve problem using simulated annealing
best_state, best_fitness = mlrose.simulated_annealing(peak_problem, schedule = schedule,
                                                      max_attempts = 10, max_iters = 1000,
                                                      init_state = init_state, random_state = 1)

print(best_state)

print(best_fitness)

[1 1 1 0 0 0 0 0 0 0 0 0]
21.0


### Combine

In [10]:
def peaks_compare(n = 12, runs = 100):
    
    # define problem
    fitness = mlrose.FourPeaks(t_pct=0.15)
    problem = mlrose.DiscreteOpt(length = n, fitness_fn = fitness, maximize = True, max_val = 2)
    
    # randomly define initial states
    np.random.seed(2)
    RHC_accu = []
    SA_accu = []
    GA_accu = []
    MIMIC_accu = []
    
    for i in range(runs):
        init_state = np.random.randint(low = 0, high = 2, size = n)
        RHC_state, RHC_fitness = mlrose.random_hill_climb(problem, max_attempts = 10, 
                                                      max_iters = 1000, restarts = 10,
                                                      init_state = init_state, curve = False, random_state = 1)
        schedule = mlrose.ExpDecay()
        SA_state, SA_fitness = mlrose.simulated_annealing(problem, schedule = schedule,
                                                              max_attempts = 10, max_iters = 1000,
                                                              init_state = init_state, random_state = 1)
        
        GA_state, GA_fitness = mlrose.genetic_alg(problem, pop_size = 200, 
                                                mutation_prob = 0.1, max_attempts = 10, max_iters = 1000, 
                                                curve = False, random_state = 1)

        MIMIC_state, MIMIC_fitness = mlrose.genetic_alg(problem, pop_size = 200, 
                                                mutation_prob = 0.1, max_attempts = 10, max_iters = 1000, 
                                                curve = False, random_state = 1)
        
        RHC_accu.append(RHC_fitness)
        SA_accu.append(SA_fitness)
        GA_accu.append(GA_fitness)
        MIMIC_accu.append(MIMIC_fitness)
    
    print(RHC_state, RHC_fitness, SA_state, SA_fitness, GA_state, GA_fitness, MIMIC_state, MIMIC_fitness)
    return [RHC_accu, SA_accu, GA_accu, MIMIC_accu]
        

In [31]:
fitness = mlrose.FourPeaks(t_pct=0.15)
state = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0])
fitness.evaluate(state)
# max 21
peaks_res = peaks_compare(12, runs = 1000)
print('RHC', np.mean(peaks_res[0]))
print('SA', np.mean(peaks_res[1]))
print('GA', np.mean(peaks_res[2]))
print('MIMIC', np.mean(peaks_res[3]))

[0 0 1 1 0 0 0 0 0 0 0 0] 8.0 [1 1 1 1 0 0 0 0 0 0 0 0] 20.0 [1 1 1 1 1 1 1 1 1 0 0 0] 21.0 [1 1 1 1 1 1 1 1 1 0 0 0] 21.0
RHC 8.013
SA 20.001
GA 21.0
MIMIC 21.0


# FlipFlop

In [205]:
fitness = mlrose.FlipFlop()
state = np.array([0, 1, 0, 1, 0, 1, 0])
fitness.evaluate(state)

6

In [206]:
def flipflop_compare(n = 12, runs = 100):
    
    # define problem
    fitness = mlrose.FlipFlop()
    problem = mlrose.DiscreteOpt(length = n, fitness_fn = fitness, maximize = True, max_val = 2)
    
    # randomly define initial states
    np.random.seed(2)
    RHC_accu = []
    SA_accu = []
    GA_accu = []
    MIMIC_accu = []
    
    for i in range(runs):
        init_state = np.random.randint(low = 0, high = 2, size = n)
        RHC_state, RHC_fitness = mlrose.random_hill_climb(problem, max_attempts = 10, 
                                                      max_iters = 1000, restarts = 10,
                                                      init_state = init_state, curve = False, random_state = 1)
        schedule = mlrose.ExpDecay()
        SA_state, SA_fitness = mlrose.simulated_annealing(problem, schedule = schedule,
                                                              max_attempts = 10, max_iters = 1000,
                                                              init_state = init_state, random_state = 1)
        
        GA_state, GA_fitness = mlrose.genetic_alg(problem, pop_size = 200, 
                                                mutation_prob = 0.1, max_attempts = 10, max_iters = 1000, 
                                                curve = False, random_state = 1)

        MIMIC_state, MIMIC_fitness = mlrose.genetic_alg(problem, pop_size = 200, 
                                                mutation_prob = 0.1, max_attempts = 10, max_iters = 1000, 
                                                curve = False, random_state = 1)
        
        RHC_accu.append(RHC_fitness)
        SA_accu.append(SA_fitness)
        GA_accu.append(GA_fitness)
        MIMIC_accu.append(MIMIC_fitness)
    
    print(RHC_state, RHC_fitness, SA_state, SA_fitness, GA_state, GA_fitness, MIMIC_state, MIMIC_fitness)
    return [RHC_accu, SA_accu, GA_accu, MIMIC_accu]
        

In [216]:
fitness = mlrose.FlipFlop()
state = np.array([1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0])
print(fitness.evaluate(state))
# max 19 
flipflop_res = flipflop_compare(30, runs = 1000)
print('RHC', np.mean(flipflop_res[0]))
print('SA', np.mean(flipflop_res[1]))
print('GA', np.mean(flipflop_res[2]))
print('MIMIC', np.mean(flipflop_res[3]))

19
[1 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 0] 25.0 [1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1] 26.0 [1 0 1 1 0 1 0 1 1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 1 0 1] 24.0 [1 0 1 1 0 1 0 1 1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 1 0 1] 24.0
RHC 24.997
SA 26.0
GA 24.0
MIMIC 24.0


In [214]:
fitness = mlrose.FlipFlop()
state = np.array([0,0,1,0,1,1])
print(fitness.evaluate(state))

3


# NN weight

In [220]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
import numpy as np
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

In [218]:
# Load the Iris dataset
data = load_iris()

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, \
                                                    test_size = 0.2, random_state = 3)

# Normalize feature data
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# One hot encode target values
one_hot = OneHotEncoder()

y_train_hot = one_hot.fit_transform(y_train.reshape(-1, 1)).todense()
y_test_hot = one_hot.transform(y_test.reshape(-1, 1)).todense()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [232]:
# Initialize neural network object and fit object
nn_model1 = mlrose.NeuralNetwork(hidden_nodes = [100], activation = 'relu', \
                                 algorithm = 'random_hill_climb', max_iters = 10000, \
                                 bias = True, is_classifier = True, learning_rate = 0.0001, \
                                 early_stopping = True, clip_max = 5, restarts = 10, \
                                 max_attempts = 100, random_state = 3)

nn_model1.fit(X_train_scaled, y_train_hot)
# Predict labels for train set and assess accuracy
y_train_pred = nn_model1.predict(X_train_scaled)

y_train_accuracy = accuracy_score(y_train_hot, y_train_pred)

print(y_train_accuracy)
0.45

# Predict labels for test set and assess accuracy
y_test_pred = nn_model1.predict(X_test_scaled)

y_test_accuracy = accuracy_score(y_test_hot, y_test_pred)

print(y_test_accuracy)

0.3416666666666667
0.4


In [233]:
nn_model1 = mlrose.NeuralNetwork(hidden_nodes = [100], activation = 'relu', \
                                 algorithm = 'genetic_alg', max_iters = 10000, \
                                 bias = True, is_classifier = True, learning_rate = 0.0001, \
                                 early_stopping = True, clip_max = 5, \
                                 max_attempts = 100, random_state = 3)

nn_model1.fit(X_train_scaled, y_train_hot)
# Predict labels for train set and assess accuracy
y_train_pred = nn_model1.predict(X_train_scaled)

y_train_accuracy = accuracy_score(y_train_hot, y_train_pred)

print(y_train_accuracy)
0.45

# Predict labels for test set and assess accuracy
y_test_pred = nn_model1.predict(X_test_scaled)

y_test_accuracy = accuracy_score(y_test_hot, y_test_pred)

print(y_test_accuracy)

0.8916666666666667
0.9333333333333333


In [234]:
nn_model1 = mlrose.NeuralNetwork(hidden_nodes = [100], activation = 'relu', \
                                 algorithm = 'simulated_annealing', max_iters = 10000, \
                                 bias = True, is_classifier = True, learning_rate = 0.0001, \
                                 early_stopping = True, clip_max = 5, \
                                 max_attempts = 100, random_state = 3)

nn_model1.fit(X_train_scaled, y_train_hot)
# Predict labels for train set and assess accuracy
y_train_pred = nn_model1.predict(X_train_scaled)

y_train_accuracy = accuracy_score(y_train_hot, y_train_pred)

print(y_train_accuracy)
0.45

# Predict labels for test set and assess accuracy
y_test_pred = nn_model1.predict(X_test_scaled)

y_test_accuracy = accuracy_score(y_test_hot, y_test_pred)

print(y_test_accuracy)

0.3333333333333333
0.36666666666666664


In [235]:
nn_model2 = mlrose.NeuralNetwork(hidden_nodes = [100], activation = 'relu', \
                                 algorithm = 'gradient_descent', max_iters = 10000, \
                                 bias = True, is_classifier = True, learning_rate = 0.0001, \
                                 early_stopping = True, clip_max = 5, max_attempts = 100, \
                                 random_state = 3)

nn_model2.fit(X_train_scaled, y_train_hot)

# Predict labels for train set and assess accuracy
y_train_pred = nn_model2.predict(X_train_scaled)

y_train_accuracy = accuracy_score(y_train_hot, y_train_pred)

print(y_train_accuracy)
0.625

# Predict labels for test set and assess accuracy
y_test_pred = nn_model2.predict(X_test_scaled)

y_test_accuracy = accuracy_score(y_test_hot, y_test_pred)

print(y_test_accuracy)

0.975
1.0
